name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          # SSH connection options for better security
          timeout: 30s
          command_timeout: 10m
          script: |
            set -e
            echo "Starting remote deployment on $HOST"

            # Load nvm (if you use nvm on the server)
            export NVM_DIR="$HOME/.nvm"
            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
              # Optionally choose a node version
              # nvm use --lts || true
            fi

            cd /root/foodDeliver/projectFront

            # Ensure we are on the correct branch and up-to-date
            git fetch --all
            git reset --hard origin/master

            # Install deps and build
            npm ci
            npm run build

            # Restart app with PM2 (or start if not running)
            pm2 restart fooddelivery --update-env || pm2 start ecosystem.config.json --update-env
            pm2 save

            echo "Deployment finished"
